### ISSUE TITLE
Newsletter: Input text font color is set to white making it invisble.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Evolution-MMA-Fitness#1]
![image](https://cloud.githubusercontent.com/assets/11186313/18260207/2adbea08-741e-11e6-8913-2daaf48ba774.png)

**Comment by emmixaustralia** [comment]
Sorry we're not seeing this in Chrome. Which version are you using?

**Comment by emmixaustralia** [comment]
The font only turns white when you scroll over and 'select' it with your mouse (blue highlight, white text) - otherwise the font is always set to gray #313131

**Comment by emmixaustralia** [comment]
Resolved
